sudo: required
services:
  - docker

before_install:
  - docker build -t react-test_v1 -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true react-test_v1 npm run test

after_success:
  - docker build -t iftesum50/ifte-multi-client ./client
  - docker build -t iftesum50/ifte-multi-nginx ./nginx
  - docker build -t iftesum50/ifte-multi-server ./server
  - docker build -t iftesum50/ifte-multi-worker ./worker
 
 # docker login and push them images to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ifte-multi-client
  - docker push ifte-multi-nginx
  - docker push ifte-multi-server
  - docker push ifte-multi-worker


